- name: JQ is present
  apt:
    name: jq
    force: yes
  tags: [common]

- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]

- name: Illya - add no_proxy configuration
  replace:
    backup: yes
    dest: /etc/environment
    regexp: '^(no_proxy=\"localhost,127.0.0.1(?!.*\b{{ item.host_ip }},{{ item.host_name }}\b).*)(?=")'
    replace: '\1,{{ item.host_ip }},{{ item.host_name }}'
  with_items: "{{ hosts }}"

- name: Services are not running
  service:
    name: "{{ item }}"
    state: stopped
  ignore_errors: yes
  with_items: "{{ obsolete_services }}"
  tags: [common]
