- name: Directories are created
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    mode: 0777
    recurse: yes
    state: directory
  with_items:
    - { path: '/data/jenkins_slaves', owner: "{{ agent_user }}" }
  tags: [jenkins]
