- name: Swarm node is running
  docker_container:
    name: swarm-node
    image: swarm
    restart_policy: on-failure
    command: join --advertise={{ ip }}:2375 consul://{{ ip }}:8500/swarm
    env:
      SERVICE_NAME: swarm-node
  when: not swarm_master is defined
  tags: [swarm]

- name: Swarm master is running
  docker_container:
    name: swarm-master
    image: swarm
    ports: 2375:2375
    restart_policy: on-failure
    command: manage consul://{{ ip }}:8500/swarm
    env:
      SERVICE_NAME: swarm-master
  when: swarm_master is defined
  tags: [swarm]
