- hosts: prod
  remote_user: vagrant
  serial: 1
  roles:
    - common
    - role: docker
      vars: 
        docker_extra: "-H tcp://0.0.0.0:2375"
    - docker-compose
    - consul
    - registrator
    - consul-template
    - nginx
