- hosts: registrator
  remote_user: vagrant
  serial: 1
  vars:
    - registrator_name: registrator-consul
  roles:
    - common
    - role: docker
      vars: 
        docker_extra: "-H tcp://0.0.0.0:2375"
    - consul
    - registrator
