- hosts: swarm
  remote_user: vagrant
  serial: 1
  vars:
    - debian_version: wily
    - docker_cfg_dest: /lib/systemd/system/docker.service
    - is_systemd: true
  roles:
    - common
    - rsyslog
    - docker
#    - role: docker
#      vars: 
#        docker_extra: "-H tcp://0.0.0.0:2375"
    - consul
    - consul-template
    - swarm
    - registrator
