- name: Directories are created
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directories }}"
  tags: [consul]

- name: Files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ files }}"
  register: files
  tags: [consul]

- name: Templates are present
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{ templates }}"
  register: templates
  tags: [consul]

### Illya - changed Consul client IP params from 0.0.0.0 due errors in Consul logs 
- name: Is running
  shell: "nohup consul agent {{ consul_extra }} \
    -data-dir {{ data_dir }} \
    -config-dir {{ config_dir }} \
    -node={{ ansible_hostname }} \
    -bind={{ ip }} \
    -client={{ ip }} \
    >{{ logs_dir }}/consul.log 2>&1 &"
  tags: [consul]

- name: Consul is restarted
  shell: killall -HUP consul
  tags: [consul]
